### ISSUE TITLE
Strange graphics bug when booting Fedora 34 Beta 

### ISSUE THREAD

**Issue by oillipheist** [knazarov/homebrew-qemu-virgl#7] opened 2021-03-30 21:18 UTC
When launching Fedora 34-Beta aarch64 image with GL-ES, the colours are rendered wrong and there seems to be an issue with surfaces being rendered transparent. 
GL-ES acceleration seems to work fine with Ubuntu and Fedora 33 image, Fedora 34Beta works with GL set to off or in UTM.

![Exh4b_UW8AA7eMf](https://user-images.githubusercontent.com/78419895/113058180-ce32d000-91a5-11eb-8512-7691801ab886.jpeg)

**Comment by knazarov** [comment] 2021-03-30 21:36
Hi @oillipheist,

Yes, that's what I see as well. Just wanted to try out Gnome 40. This may or may not be the problem in the virgil3d integration, as Fedora is in beta.

I've tried to reach out to @akihikodaki (the author of macos virgil integration) but he said that he was unable to boot the aarch64 image. Maybe things have changed and it's time to test it again.

**Comment by akihikodaki** [comment] 2021-04-01 10:18
I got it booted and have done some basic investigation. Apparently the new version of Mesa adds new texture swizzling requirement to virtio-gpu-3d, which fails to meet it when displaying a texture. Later, I'll dig into the problem more to figure out a solution.

**Comment by akihikodaki** [comment] 2021-04-02 16:16
I pushed a fix to GitHub (akihikodaki/qemu@43b8afeb73be068019883c73dd99054afecdb470).

**Comment by knazarov** [comment] 2021-04-02 17:12
@akihikodaki that's great! Thank you. I'll pull the patchset into the formula.

**Comment by knazarov** [comment] 2021-04-03 12:54
@akihikodaki the new patch works for me when I use `gl=core`. But when I do `gl=es`, I see this:

<img width="1378" alt="Screenshot 2021-04-03 at 15 52 22" src="https://user-images.githubusercontent.com/6728841/113478967-c2405a00-9494-11eb-9338-ef3877b506e8.png">

Most of the windows are just slightly transparent red.

**Comment by akihikodaki** [comment] 2021-04-03 16:06
@knazarov It was my fault. I have forgotten to push a part of the fix. I have just pushed it to my repository (akihikodaki/virglrenderer@01fcbb7a8f15c63b709a79ef9d73e803e2995dde).

`gl=core` is not affected by the problem so it should work even before applying the fix.

**Comment by knazarov** [comment] 2021-04-03 20:20
@akihikodaki I've applied the patch, and now the texture is blue instead of red :)

**Comment by akihikodaki** [comment] 2021-04-04 03:14
@knazarov Well, I suspect it is a bug of a lower layer (ANGLE, Intel driver and/or hardware). If you are interested, fiddle with: https://github.com/akihikodaki/virglrenderer/commit/01fcbb7a8f15c63b709a79ef9d73e803e2995dde#diff-f9ec2e109236d40360f659ae49f3d1ad43f7608c6b62c0520a1765b850bb572dR10661

**Comment by oillipheist** [comment] 2021-04-04 09:51
core profile doesn't seem to work on M1 here at all, have it working on ubuntu but seems broken on both fedora 33 and fedora 34beta

**Comment by akihikodaki** [comment] 2021-04-04 12:39
I have core profile work with Fedora 33. My command line is:
```
qemu-system-aarch64 -machine virt,accel=hvf,highmem=off -cpu cortex-a72 -smp 8 -m 14336 -drive if=pflash,format=raw,file=/Users/person/fedora/drive/edk2-aarch64-code.fd,readonly=on -drive if=pflash,format=raw,file=/Users/person/fedora/drive/edk2-arm-vars.fd,discard=on -drive id=virtio,if=none,format=raw,file=/Users/person/fedora/drive/virtio.raw,discard=on -device intel-hda -device hda-output -device virtio-gpu-pci -device virtio-net-device,netdev=net -device virtio-mouse-pci -device virtio-keyboard-pci -device virtio-blk-device,drive=virtio -device virtio-rng-device -display cocoa,gl=core -netdev user,id=net -full-screen -runas 501:20
```

**Comment by oillipheist** [comment] 2021-04-05 18:07
hmm.. Tried that and got 

> qemu-system-aarch64: Failed to setgroups(1, [20])

**Comment by akihikodaki** [comment] 2021-04-09 02:26
@oillipheist 

> hmm.. Tried that and got
> 
> > qemu-system-aarch64: Failed to setgroups(1, [20])

The command line requires root to run. Use sudo, or modify the command line (and please share it if you got the problem reproduced with.)

**Comment by knazarov** [comment] 2021-04-10 19:54
@oillipheist I’ve merged @akihikodaki’s newer changeset to master, but I can’t check it, since I’m without a computer for at least 10 days.

**Comment by knazarov** [comment] 2021-04-27 22:35
I’ve got my computer back, and will soon be trying Fedora 34, now that it’s released :)

**Comment by akihikodaki** [comment] 2021-04-28 03:36
I added yet another fix to virglrenderer (see https://gist.github.com/akihikodaki/87df4149e7ca87f18dc56807ec5a1bc5#gistcomment-3722509 for details). I'll use Fedora 34 for daily use from now.

**Comment by knazarov** [comment] 2021-04-28 17:41
I’ve pulled your fixes, thanks!

**Comment by hexdump0815** [comment] 2021-04-29 06:51
not sure if it was due to this, but since i updated to the latest version now also the lightdm slick greater is working well - before it was just full screen gray and now there is a proper login window :)

**Comment by knazarov** [comment] 2021-04-30 21:55
Fedora 34 now works with the latest patch and is quite smooth. Just checked it on my mac.

**Closed by knazarov** 2021-04-30 21:55 UTC
