### ISSUE TITLE
Error during brew install on m1 mbp

### ISSUE THREAD

**Issue by mcfearsome** [knazarov/homebrew-qemu-virgl#23] opened 2021-05-17 16:54 UTC
```
==> Installing knazarov/qemu-virgl/qemu-virgl dependency: knazarov/qemu-virgl/libangl
/opt/homebrew/Library/Taps/knazarov/homebrew-qemu-virgl/Formula/libangle.rb:26: warning: conflicting chdir during another chdir block
==> python2 scripts/bootstrap.py
==> gclient sync
Last 15 lines from /Users/mcfearsome/Library/Logs/Homebrew/libangle/02.gclient:
gclient
sync


________ running 'cipd ensure -log-level error -root /private/tmp/libangle-20210517-19041-qw0d6e -ensure-file /private/tmp/tmpjo1sbjcp.ensure' in '.'
Errors:
  failed to resolve infra/tools/luci/isolate/mac-arm64@git_revision:fd10124659e991321df2f8a5d3749687b54ceb0a (line 10): no such tag
  failed to resolve infra/tools/luci/isolated/mac-arm64@git_revision:fd10124659e991321df2f8a5d3749687b54ceb0a (line 11): no such tag
  failed to resolve infra/tools/luci/swarming/mac-arm64@git_revision:fd10124659e991321df2f8a5d3749687b54ceb0a (line 12): no such tag
Error: Command 'cipd ensure -log-level error -root /private/tmp/libangle-20210517-19041-qw0d6e -ensure-file /private/tmp/tmpjo1sbjcp.ensure' returned non-zero exit status 1
Errors:
  failed to resolve infra/tools/luci/isolate/mac-arm64@git_revision:fd10124659e991321df2f8a5d3749687b54ceb0a (line 10): no such tag
  failed to resolve infra/tools/luci/isolated/mac-arm64@git_revision:fd10124659e991321df2f8a5d3749687b54ceb0a (line 11): no such tag
  failed to resolve infra/tools/luci/swarming/mac-arm64@git_revision:fd10124659e991321df2f8a5d3749687b54ceb0a (line 12): no such tag
```

Have looked through the closed issues and haven't found anything helpful, thanks in advance for any guidance.

**Comment by knazarov** [comment] 2021-05-17 16:58
It looks like the problem may be transient with google tools. Please try again in an hour.

**Comment by mcfearsome** [comment] 2021-05-17 17:09
Great! Thanks for the quick reply, I'll try again at the end of my day in a few hours

**Comment by mcfearsome** [comment] 2021-05-18 17:45
hey there again, so this has persisted...

any thoughts to point me in the right direction? I don't have a problem going down a rabbit hole, just need a little shove in the right direction

**Comment by knazarov** [comment] 2021-05-18 21:46
Try to do this:

```sh
git clone https://chromium.googlesource.com/angle/angle
cd angle
python2 scripts/bootstrap.py
gclient sync
```

Let’s see if it reproduces on the latest version of angle.

**Comment by cjahv** [comment] 2021-05-19 09:26
Use the latest angle to get the
```
________ running 'vpython build/mac_toolchain.py' in '/Users/jahv/Documents/qemu/source/angle/.'
[E2021-05-19T17:20:13.212819+08:00 40636 0 venv.go:975] Command (cwd=/var/folders/nw/0tjfp_vs1zd25vgqgp0_7sww0000gn/T/034962693): [/Users/jahv/.vpython-root/3077d9/bin/python -B -E -s -m pip install --isolated --compile --no-index --find-links /var/folders/nw/0tjfp_vs1zd25vgqgp0_7sww0000gn/T/vpython_bootstrap327805505/packages --requirement /var/folders/nw/0tjfp_vs1zd25vgqgp0_7sww0000gn/T/vpython_bootstrap327805505/requirements.txt --no-binary=:none: --only-binary=:all: --use-wheel]
Process output:
Collecting atomicwrites==1.3.0 (from -r /var/folders/nw/0tjfp_vs1zd25vgqgp0_7sww0000gn/T/vpython_bootstrap327805505/requirements.txt (line 1))
Collecting attrs==17.4.0 (from -r /var/folders/nw/0tjfp_vs1zd25vgqgp0_7sww0000gn/T/vpython_bootstrap327805505/requirements.txt (line 2))
Collecting blessings==1.7 (from -r /var/folders/nw/0tjfp_vs1zd25vgqgp0_7sww0000gn/T/vpython_bootstrap327805505/requirements.txt (line 3))
Collecting boto==2.48.0 (from -r /var/folders/nw/0tjfp_vs1zd25vgqgp0_7sww0000gn/T/vpython_bootstrap327805505/requirements.txt (line 4))
Collecting certifi==2018.11.29 (from -r /var/folders/nw/0tjfp_vs1zd25vgqgp0_7sww0000gn/T/vpython_bootstrap327805505/requirements.txt (line 5))
Collecting chardet==3.0.4 (from -r /var/folders/nw/0tjfp_vs1zd25vgqgp0_7sww0000gn/T/vpython_bootstrap327805505/requirements.txt (line 6))
Collecting colorama==0.4.1 (from -r /var/folders/nw/0tjfp_vs1zd25vgqgp0_7sww0000gn/T/vpython_bootstrap327805505/requirements.txt (line 7))
Collecting coverage==4.3.4 (from -r /var/folders/nw/0tjfp_vs1zd25vgqgp0_7sww0000gn/T/vpython_bootstrap327805505/requirements.txt (line 8))
  Could not find a version that satisfies the requirement coverage==4.3.4 (from -r /var/folders/nw/0tjfp_vs1zd25vgqgp0_7sww0000gn/T/vpython_bootstrap327805505/requirements.txt (line 8)) (from versions: )
No matching distribution found for coverage==4.3.4 (from -r /var/folders/nw/0tjfp_vs1zd25vgqgp0_7sww0000gn/T/vpython_bootstrap327805505/requirements.txt (line 8))

Environment:
AUTOJUMP_ERROR_PATH=/Users/jahv/Library/autojump/errors.log
AUTOJUMP_SOURCED=1
COLORFGBG=0;15
COLORTERM=truecolor
COMMAND_MODE=unix2003
DISPLAY=/private/tmp/com.apple.launchd.GHrVkazg11/org.xquartz:0
GRADLE_HOME=/Users/jahv/.sdkman/candidates/gradle/current
HOME=/var/folders/nw/0tjfp_vs1zd25vgqgp0_7sww0000gn/T/vpython_bootstrap327805505
HOMEBREW_CELLAR=/opt/homebrew/Cellar
HOMEBREW_PREFIX=/opt/homebrew
HOMEBREW_REPOSITORY=/opt/homebrew
INFOPATH=/opt/homebrew/share/info:
ITERM_PROFILE=Default
ITERM_SESSION_ID=w0t0p0:4144C817-7A14-4BB5-8794-408BDF441FCB
LANG=en_US.UTF-8
LC_TERMINAL=iTerm2
LC_TERMINAL_VERSION=3.4.6
LESS=-R
LOGNAME=jahv
LSCOLORS=Gxfxcxdxbxegedabagacad
LaunchInstanceID=85FD8956-5C15-45A4-BDAB-1280C857D05D
MANPATH=/opt/homebrew/share/man::
P9K_SSH=0
P9K_TTY=old
PAGER=less
PATH=/Users/jahv/Documents/qemu/depot_tools:/Users/jahv/.sdkman/candidates/gradle/current/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/opt/X11/bin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/jahv/.fzf/bin:/Users/jahv/Documents/qemu/depot_tools
PIP_NO_BINARY=:none:
PIP_ONLY_BINARY=:all:
PIP_USE_WHEEL=1
PWD=/Users/jahv/Documents/qemu/source/angle
PYTHONDONTWRITEBYTECODE=1
PYTHONNOUSERSITE=1
SDKMAN_CANDIDATES_API=https://api.sdkman.io/2
SDKMAN_CANDIDATES_DIR=/Users/jahv/.sdkman/candidates
SDKMAN_DIR=/Users/jahv/.sdkman
SDKMAN_PLATFORM=DarwinX64
SDKMAN_VERSION=5.11.0+644
SECURITYSESSIONID=186a6
SHELL=/bin/zsh
SHLVL=2
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.451JJaToO4/Listeners
TERM=xterm-256color
TERM_PROGRAM=iTerm.app
TERM_PROGRAM_VERSION=3.4.6
TERM_SESSION_ID=w0t0p0:4144C817-7A14-4BB5-8794-408BDF441FCB
TMPDIR=/var/folders/nw/0tjfp_vs1zd25vgqgp0_7sww0000gn/T/
USER=jahv
VIRTUAL_ENV=/Users/jahv/.vpython-root/ba3fca
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
ZSH=/Users/jahv/.oh-my-zsh
_P9K_TTY=/dev/ttys000
__CFBundleIdentifier=com.googlecode.iterm2
__CF_USER_TEXT_ENCODING=0x1F5:0x19:0x34
```

**Comment by IonAgorria** [comment] 2021-05-20 09:35
I added the arm64 bottle SHA to workaround this and install libangle without compiling
https://github.com/IonAgorria/homebrew-qemu-virgl/blob/master/Formula/libangle.rb#L10

Had to remove rebuild 1 since the bottle doesnt have .1 at the end, I guess uploading bottle with .1.tar.gz would also work

**Comment by knazarov** [comment] 2021-05-20 09:37
@IonAgorria maybe I should manually add the bottles, given how flaky the google tooling is…

**Comment by thomasfchang** [comment] 2021-05-20 09:53
I am running in to the same issue. I tried

```
git clone https://chromium.googlesource.com/angle/angle
cd angle
python2 scripts/bootstrap.py
gclient sync
```
with no success. I am a bit of a noob though so don't know how to fix it... Would be great if it could be solved!

**Comment by mcfearsome** [comment] 2021-05-20 13:57
I also didn't have any luck cloning and bootstrapping locally

**Comment by knazarov** [comment] 2021-05-20 22:34
Please try:

```
brew tap --force-auto-update knazarov/qemu-virgl
brew install qemu-virgl
```

I’ve uploaded binary bottles, and now you shouldn’t need to compile libangle from source.

**Comment by thomasfchang** [comment] 2021-05-20 22:56
Thanks for fixing it! That definitely seems to have done something. Currently it is hanging for me here. Will update if it changes.

`==> Applying qemu-edid-v01.diff
patching file hw/display/edid-generate.c
Hunk #1 succeeded at 45 (offset 1 line).
Hunk #2 succeeded at 159 (offset 1 line).
Hunk #3 succeeded at 210 (offset 1 line).
Hunk #4 succeeded at 237 (offset 1 line).
Hunk #5 succeeded at 317 (offset 1 line).
Hunk #6 succeeded at 387 (offset 1 line).
Hunk #7 succeeded at 407 (offset 1 line).
Hunk #8 succeeded at 477 (offset 1 line).
Hunk #9 succeeded at 508 (offset 1 line).
patching file hw/display/vga-pci.c
patching file qemu-edid.c
==> ./configure --prefix=/opt/homebrew/Cellar/qemu-virgl/20210507.1 --cc=clang -
==> make V=1 install`

**Comment by thomasfchang** [comment] 2021-05-20 23:03
I get an error:

`Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /opt/homebrew
Could not symlink bin/elf2dmp
Target /opt/homebrew/bin/elf2dmp
is a symlink belonging to qemu. You can unlink it:
  brew unlink qemu

To force the link and overwrite all conflicting files:
  brew link --overwrite qemu-virgl

To list all files that would be deleted:
  brew link --overwrite --dry-run qemu-virgl

Possible conflicting files are:
/opt/homebrew/bin/elf2dmp -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/elf2dmp
/opt/homebrew/bin/qemu-edid -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-edid
/opt/homebrew/bin/qemu-img -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-img
/opt/homebrew/bin/qemu-io -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-io
/opt/homebrew/bin/qemu-nbd -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-nbd
/opt/homebrew/bin/qemu-storage-daemon -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-storage-daemon
/opt/homebrew/bin/qemu-system-aarch64 -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-aarch64
/opt/homebrew/bin/qemu-system-alpha -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-alpha
/opt/homebrew/bin/qemu-system-arm -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-arm
/opt/homebrew/bin/qemu-system-avr -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-avr
/opt/homebrew/bin/qemu-system-cris -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-cris
/opt/homebrew/bin/qemu-system-hppa -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-hppa
/opt/homebrew/bin/qemu-system-i386 -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-i386
/opt/homebrew/bin/qemu-system-m68k -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-m68k
/opt/homebrew/bin/qemu-system-microblaze -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-microblaze
/opt/homebrew/bin/qemu-system-microblazeel -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-microblazeel
/opt/homebrew/bin/qemu-system-mips -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-mips
/opt/homebrew/bin/qemu-system-mips64 -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-mips64
/opt/homebrew/bin/qemu-system-mips64el -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-mips64el
/opt/homebrew/bin/qemu-system-mipsel -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-mipsel
/opt/homebrew/bin/qemu-system-moxie -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-moxie
/opt/homebrew/bin/qemu-system-nios2 -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-nios2
/opt/homebrew/bin/qemu-system-or1k -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-or1k
/opt/homebrew/bin/qemu-system-ppc -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-ppc
/opt/homebrew/bin/qemu-system-ppc64 -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-ppc64
/opt/homebrew/bin/qemu-system-riscv32 -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-riscv32
/opt/homebrew/bin/qemu-system-riscv64 -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-riscv64
/opt/homebrew/bin/qemu-system-rx -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-rx
/opt/homebrew/bin/qemu-system-s390x -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-s390x
/opt/homebrew/bin/qemu-system-sh4 -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-sh4
/opt/homebrew/bin/qemu-system-sh4eb -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-sh4eb
/opt/homebrew/bin/qemu-system-sparc -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-sparc
/opt/homebrew/bin/qemu-system-sparc64 -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-sparc64
/opt/homebrew/bin/qemu-system-tricore -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-tricore
/opt/homebrew/bin/qemu-system-x86_64 -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-x86_64
/opt/homebrew/bin/qemu-system-xtensa -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-xtensa
/opt/homebrew/bin/qemu-system-xtensaeb -> /opt/homebrew/Cellar/qemu/5.2.0_1/bin/qemu-system-xtensaeb
/opt/homebrew/share/applications/qemu.desktop -> /opt/homebrew/Cellar/qemu/5.2.0_1/share/applications/qemu.desktop
/opt/homebrew/share/icons/hicolor/128x128/apps/qemu.png -> /opt/homebrew/Cellar/qemu/5.2.0_1/share/icons/hicolor/128x128/apps/qemu.png
/opt/homebrew/share/icons/hicolor/16x16/apps/qemu.png -> /opt/homebrew/Cellar/qemu/5.2.0_1/share/icons/hicolor/16x16/apps/qemu.png
/opt/homebrew/share/icons/hicolor/24x24/apps/qemu.png -> /opt/homebrew/Cellar/qemu/5.2.0_1/share/icons/hicolor/24x24/apps/qemu.png
/opt/homebrew/share/icons/hicolor/256x256/apps/qemu.png -> /opt/homebrew/Cellar/qemu/5.2.0_1/share/icons/hicolor/256x256/apps/qemu.png
/opt/homebrew/share/icons/hicolor/32x32/apps/qemu.bmp -> /opt/homebrew/Cellar/qemu/5.2.0_1/share/icons/hicolor/32x32/apps/qemu.bmp
/opt/homebrew/share/icons/hicolor/32x32/apps/qemu.png -> /opt/homebrew/Cellar/qemu/5.2.0_1/share/icons/hicolor/32x32/apps/qemu.png
/opt/homebrew/share/icons/hicolor/48x48/apps/qemu.png -> /opt/homebrew/Cellar/qemu/5.2.0_1/share/icons/hicolor/48x48/apps/qemu.png
/opt/homebrew/share/icons/hicolor/512x512/apps/qemu.png -> /opt/homebrew/Cellar/qemu/5.2.0_1/share/icons/hicolor/512x512/apps/qemu.png
/opt/homebrew/share/icons/hicolor/64x64/apps/qemu.png -> /opt/homebrew/Cellar/qemu/5.2.0_1/share/icons/hicolor/64x64/apps/qemu.png
/opt/homebrew/share/icons/hicolor/scalable/apps/qemu.svg -> /opt/homebrew/Cellar/qemu/5.2.0_1/share/icons/hicolor/scalable/apps/qemu.svg
Error: Could not symlink share/qemu/QEMU,cgthree.bin
Target /opt/homebrew/share/qemu/QEMU,cgthree.bin
is a symlink belonging to qemu. You can unlink it:
  brew unlink qemu

To force the link and overwrite all conflicting files:
  brew link --overwrite qemu

To list all files that would be deleted:
  brew link --overwrite --dry-run qemu`

**Comment by 0xqoob** [comment] 2021-05-20 23:04
Try `brew uninstall qemu`?

**Comment by knazarov** [comment] 2021-05-20 23:04
You need to uninstall existing qemu, and then try again.

**Comment by thomasfchang** [comment] 2021-05-20 23:06
Reinstall qemu and then try again? Or is qemu included in this project?

**Comment by knazarov** [comment] 2021-05-20 23:10
You have qemu already installed. The formula in this repo is a full (but patched) qemu. So they conflict. Remove your existing qemu with `brew uninstall qemu` then do `brew reinstall qemu-virgl`

**Comment by knazarov** [comment] 2021-05-22 08:38
Just wanted to follow-up on this issue. Did anyone have any success with installation after the recent fix?

**Comment by cjahv** [comment] 2021-05-22 08:39
Installation succeeded

**Comment by knazarov** [comment] 2021-05-22 08:49
OK, thank you! I’m closing this ticket then unless further reports resurface.

**Closed by knazarov** 2021-05-22 08:49 UTC
